title: Coding Notes
description: Coding notes on Erlang, Elixir and Go
twitter_username: niamtokik
theme: jekyll-theme-architect
markdown: kramdown

sass:
  style: compressed

url: "http://niamtokik.github.io"
